name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: "temurin"

    - name: Grant execute permission for gradlew
      run: chmod +x SyzygyEvents/gradlew

    - name: Build with Gradle
      working-directory: ./SyzygyEvents
      run: ./gradlew build
      
    - name: Run Unit Tests
      working-directory: ./SyzygyEvents
      run: ./gradlew test
